### ISSUE TITLE
Empty line between todo list items

### ISSUE THREAD

**Issue by notflip** [primary-theme/obsidian#114]
**First of all, this is the best theme I've ever come across, it's stunning.**

There's a small issue with 2 todo items in preview mode having an extra empty line between them.

_edit mode_
<img width="270" alt="Screenshot 2022-04-06 at 09 29 30" src="https://user-images.githubusercontent.com/4146384/161919804-50fdb2ac-6037-40bd-a4d1-5e4e71737dbf.png">

_preview mode_
<img width="289" alt="Screenshot 2022-04-06 at 09 29 35" src="https://user-images.githubusercontent.com/4146384/161919797-eadc2b55-2c62-46c9-be9d-7ab043eb9796.png">

**Comment by stoneskipping** [comment]
I'm not having the same problem with Primary, but I did have an issue like this before with Obsidian in general. 🤔

Do you think your issue might be related to this? https://forum.obsidian.md/t/how-to-leave-gaps-between-some-items-in-a-list/18221

If so, you can put `<br>` on empty lines between separate bulleted/checkbox lists to fix the problem (or use the other solutions in the thread I linked). 😄

**Comment by ceciliamay** [comment]
Hello there! Sorry for the late reply. I've never had this issue with the checkboxes and I haven't really styled anything around list spacing so it might be an obsidian issue. It's working as it should on my end:
LP:
![image](https://user-images.githubusercontent.com/90643719/164952163-3bc962d2-f308-484d-a0c3-69bc3420b262.png)
Preview:
![image](https://user-images.githubusercontent.com/90643719/164952169-5bc05164-e2c9-4e40-9ef6-e904059334a2.png)

the spacing between the header and the list is as expected due to how obsidian adds a margin for every block on preview mode. but i definitely do not have spacing issues within the list.

suggestions:
- can you check if you have any snippets of plugins affecting this? if none,
- can you try reinstalling the theme? if not,
- is your obsidian up to date with the latest release? if not, maybe updating might solve it!
- if these 3 suggestions fail, can you try reinstalling obsidian? this has solution has worked for some users in the past 🤔

**Comment by ceciliamay** [comment]
Hello there! Is this still an occuring issue @notflip ? If yes let me know, if not - I will close this issue!
