### ISSUE TITLE
Improve design for multi-pane Notes

### ISSUE THREAD

**Issue by ceciliamay** [primary-theme/obsidian#195]
![Image](https://github.com/primary-theme/obsidian/assets/90643719/bad38815-b89e-4157-8493-092589f50c56)

![Image](https://github.com/primary-theme/obsidian/assets/90643719/3caf22e2-62ae-4d53-ba51-602705903a59)

Less lines would be better I think... or maybe experiment with different design options. Smaller handle? No lines but have tiny margins + cursor change on hover?

**Comment by ceciliamay** [comment]
Lacks margin-left, margin-right in this layout

![Image](https://github.com/primary-theme/obsidian/assets/90643719/ef8a75ae-614d-4cd5-8c80-43e3666b7ed2)

**Comment by ceciliamay** [comment]
See border-radius not being consistent, borders not consistent, alignment/padding/margin not consistent.

![Image](https://github.com/primary-theme/obsidian/assets/90643719/c8332c86-eeae-48b7-92a7-d96576053128)

The big horizontal resize handle doesn't look that good in this setup -- making me believe a smaller handle in the middle might be better.

**Comment by FREYA265** [comment]
Hi ^^ yes I had that too ^^
I think you need a bit of internal margin like the example below which makes it clearer, but not that much. (border theme)
![image](https://github.com/primary-theme/obsidian/assets/139784879/8ecd56a1-3570-430c-827d-18c10c32a27f)


Because currently it's true that there is a bit of overlap :) 
![image](https://github.com/primary-theme/obsidian/assets/139784879/4d38f0c5-9617-4238-8bd9-e3fb5f1b7356)
Thanks for your work

**Comment by ceciliamay** [comment]
Found a really really good fix for (I think) all use cases for multi-pane!! Will release in this week's beta 🥳 Would love for you guys to test it out and see if there's any more use cases I haven't covered.

![Image](https://github.com/primary-theme/obsidian/assets/90643719/b6461e88-968c-42b0-9598-e81ce214e3c9)
