### ISSUE TITLE
Plugin support for Excalidraw

### ISSUE THREAD

**Issue by koenbunders** [primary-theme/obsidian#61]
Request: Plugin support for Excalidraw (dark mode + light mode)

**Comment by Mux-Mastermann** [comment]
![image](https://user-images.githubusercontent.com/43514294/176138280-6f90d061-ca9f-4fca-a105-4e04788543b1.png)

![image](https://user-images.githubusercontent.com/43514294/176138602-d9caf113-29f6-4c45-95a5-8d2924f6e340.png)

You made a really great theme, thank you for that! But Excalidraw is also a really great plugin. Can we get a fix for the issue with some buttons showing as black boxes in Excalidraw light mode?

**Comment by Mux-Mastermann** [comment]
Are you planning to support this plugin in the future? Or do you have any tips on how to solve this problem (maybe via style settings)? @ceciliamay
Thanks a lot in advance!

**Comment by ceciliamay** [comment]
Hello @Mux-Mastermann !! Sorry for the late reply - I will be fixing this in the next update. I'm bumping this up due to the high demand and I appreciate you all for reporting these issues since I don't personally use Excalidraw. Next update should be after 0.16 comes out. Thank you for your patience guys!!

**Comment by ceciliamay** [comment]
color variables (at html level):
- `--color-primary`
- `--color-on-primary-container`
- `--color-surface-primary-container`
- `--color-primary-darkest`
- `--islang-bg-color`

only change the accented colors, not the ui colors because excalidraw kind of uses it and changes it when canvas bg is changed

**Comment by ceciliamay** [comment]
there doesn't seem to be a way for me to improve excalidraw's interface. the coloring is hard coded into the app and it's very difficult to style it, and i can't seem to override it without it getting ugly in the code. i also think there will be more changes to the interface in the future, so i will drop "enhanced" support for excalidraw.

in conclusion i think it would be troublesome to mold it to what i think it should look like, and then maintain it. so i will leave it to the creator!

it looks better now than it did back in 2022 though, so i hope the current ui design suffices. thank you to those who posted this! i will close this now.
